"use client";
import { useEffect, useId, useRef } from "react";
import { useReducedMotion } from "motion/react";

// Humpback whale swim cycle from the whale kit (CC BY 4.0, see /THIRD_PARTY_NOTICES.txt),
// drawn in the style of the kit's ink showcase render.
//
// whaleInk.json holds 30 keyframes (periodic cubic B-spline) of the mesh vertices this
// drawing tracks, plus static ink artwork in rest-frame coordinates:
//   - the body is a smooth closed curve through a ring of outline vertices,
//   - the throat strands/pleats are clipped to that live body outline,
//   - the fin art follows a least-squares affine fit of its vertices,
//   - the fluke art is anchored between the tail stock and tail tip of that outline.
// The data file is generated by scripts/whale/build-whale-ink.mjs (`npm run whale:build`, see
// scripts/whale/README.md); this component only animates it.

type WhaleInk = {
    frames: number[][]; // per keyframe: x,y of each tracked vertex
    ring: number[]; // body outline, as indices into the tracked vertices
    fin: number[];
    tailTip: number[]; // ring positions averaged into the tail tip
    tailStock: number[]; // ring positions averaged into the tail stock (fluke root)
    art: Record<string, string>; // d attributes, keyed by data-art name
};

// Must match the mesh bounds the data was generated with — hardcoded so the container
// has its final size before the (lazy-loaded) data arrives.
const VIEW_W = 904;
const VIEW_H = 338;

const DESKTOP = { speed: 50 }; // px per second
const MOBILE = { speed: 40 };
const BODY_LENGTHS_PER_STROKE = 1.2; // how far one tail beat carries the whale
const PATH_FRAME_MS = 33; // shape redraws capped at ~30fps; translation stays per-frame
const REST_MIN_MS = 3000;
const REST_MAX_MS = 5000;
const HEAVE = 0.012; // peak vertical body heave per tail beat, as a fraction of whale length (≈ ±2px at 171px)
const SMOOTH_PASSES = 12; // Taubin smoothing of the outline ring (removes mesh jitter without shrinking)

// Least-squares affine map from rest positions to current positions for a vertex group.
// The normal matrix only depends on the rest pose, so it's inverted once up front.
function makeAffineFit(rest: Float32Array, verts: number[]) {
    let a00 = 0, a01 = 0, a02 = 0, a11 = 0, a12 = 0, a22 = 0;
    for (const v of verts) {
        const x = rest[v * 2];
        const y = rest[v * 2 + 1];
        a00 += x * x; a01 += x * y; a02 += x; a11 += y * y; a12 += y; a22 += 1;
    }
    const c00 = a11 * a22 - a12 * a12;
    const c01 = a02 * a12 - a01 * a22;
    const c02 = a01 * a12 - a02 * a11;
    const c11 = a00 * a22 - a02 * a02;
    const c12 = a01 * a02 - a00 * a12;
    const c22 = a00 * a11 - a01 * a01;
    const det = a00 * c00 + a01 * c01 + a02 * c02;
    const i00 = c00 / det, i01 = c01 / det, i02 = c02 / det;
    const i11 = c11 / det, i12 = c12 / det, i22 = c22 / det;

    return (pos: Float32Array) => {
        let bx0 = 0, bx1 = 0, bx2 = 0, by0 = 0, by1 = 0, by2 = 0;
        for (const v of verts) {
            const x = rest[v * 2];
            const y = rest[v * 2 + 1];
            const px = pos[v * 2];
            const py = pos[v * 2 + 1];
            bx0 += x * px; bx1 += y * px; bx2 += px;
            by0 += x * py; by1 += y * py; by2 += py;
        }
        const a = i00 * bx0 + i01 * bx1 + i02 * bx2;
        const c = i01 * bx0 + i11 * bx1 + i12 * bx2;
        const e = i02 * bx0 + i12 * bx1 + i22 * bx2;
        const b = i00 * by0 + i01 * by1 + i02 * by2;
        const d = i01 * by0 + i11 * by1 + i12 * by2;
        const f = i02 * by0 + i12 * by1 + i22 * by2;
        return `matrix(${a.toFixed(4)} ${b.toFixed(4)} ${c.toFixed(4)} ${d.toFixed(4)} ${e.toFixed(2)} ${f.toFixed(2)})`;
    };
}

export default function Whale() {
    const reduceMotion = useReducedMotion();
    const id = useId().replace(/[^a-zA-Z0-9_-]/g, "");
    const containerRef = useRef<HTMLDivElement>(null);
    const wrapperRef = useRef<HTMLDivElement>(null);
    const svgRef = useRef<SVGSVGElement>(null);
    const bodyRef = useRef<SVGPathElement>(null);
    const finRef = useRef<SVGGElement>(null);
    const flukeRef = useRef<SVGGElement>(null);

    useEffect(() => {
        const container = containerRef.current;
        const wrapper = wrapperRef.current;
        const svg = svgRef.current;
        const body = bodyRef.current;
        const finGroup = finRef.current;
        const flukeGroup = flukeRef.current;
        if (!container || !wrapper || !svg || !body || !finGroup || !flukeGroup) return;

        let data: WhaleInk | null = null;
        let frames: Float32Array[] = [];
        let positions = new Float32Array(0);
        let ringX = new Float32Array(0);
        let ringY = new Float32Array(0);
        let tmpX = new Float32Array(0);
        let tmpY = new Float32Array(0);
        let segments: string[] = [];
        let fitFin: ((pos: Float32Array) => string) | null = null;
        let heave = new Float32Array(0); // per keyframe, normalised to ±1
        let disposed = false;

        let containerW = 0;
        let whaleW = 0;
        let speed = DESKTOP.speed;

        let x = 0;
        let dir = 1;
        let phase = 0; // 0..1 through the swim cycle
        let swimming = true;
        let visible = false;
        let rafId = 0;
        let lastTime = 0;
        let lastPathTime = 0;
        let restTimer: ReturnType<typeof setTimeout> | undefined;

        const drawBody = () => {
            if (!data) return;
            const ring = data.ring;
            const n = ring.length;
            for (let i = 0; i < n; i++) {
                ringX[i] = positions[ring[i] * 2];
                ringY[i] = positions[ring[i] * 2 + 1];
            }
            // Taubin smoothing: alternate shrink/inflate passes so the outline loses the
            // mesh's zig-zag without the whole whale getting thinner.
            for (let pass = 0; pass < SMOOTH_PASSES; pass++) {
                const lambda = pass % 2 ? -0.53 : 0.5;
                for (let i = 0; i < n; i++) {
                    const prev = (i - 1 + n) % n;
                    const next = (i + 1) % n;
                    tmpX[i] = ringX[i] + lambda * ((ringX[prev] + ringX[next]) / 2 - ringX[i]);
                    tmpY[i] = ringY[i] + lambda * ((ringY[prev] + ringY[next]) / 2 - ringY[i]);
                }
                [ringX, tmpX] = [tmpX, ringX];
                [ringY, tmpY] = [tmpY, ringY];
            }
            // The fluke art is drawn in a local frame running from the tail stock (0) to the
            // tail tip (1) of the smoothed outline, so it can't drift off the body.
            let sx = 0, sy = 0, tx = 0, ty = 0;
            for (const i of data.tailStock) { sx += ringX[i]; sy += ringY[i]; }
            for (const i of data.tailTip) { tx += ringX[i]; ty += ringY[i]; }
            sx /= data.tailStock.length; sy /= data.tailStock.length;
            tx /= data.tailTip.length; ty /= data.tailTip.length;
            const ax = tx - sx;
            const ay = ty - sy;
            flukeGroup.setAttribute(
                "transform",
                `matrix(${ax.toFixed(3)} ${ay.toFixed(3)} ${(-ay).toFixed(3)} ${ax.toFixed(3)} ${sx.toFixed(2)} ${sy.toFixed(2)})`,
            );
            // Closed Catmull-Rom spline through the smoothed ring, as cubic Béziers.
            for (let i = 0; i < n; i++) {
                const i0 = (i - 1 + n) % n;
                const i2 = (i + 1) % n;
                const i3 = (i + 2) % n;
                segments[i] =
                    `C${(ringX[i] + (ringX[i2] - ringX[i0]) / 6).toFixed(1)} ${(ringY[i] + (ringY[i2] - ringY[i0]) / 6).toFixed(1)} ` +
                    `${(ringX[i2] - (ringX[i3] - ringX[i]) / 6).toFixed(1)} ${(ringY[i2] - (ringY[i3] - ringY[i]) / 6).toFixed(1)} ` +
                    `${ringX[i2].toFixed(1)} ${ringY[i2].toFixed(1)}`;
            }
            body.setAttribute("d", `M${ringX[0].toFixed(1)} ${ringY[0].toFixed(1)}${segments.join("")}Z`);
        };

        const drawShape = (cyclePhase: number) => {
            if (!data || !fitFin) return;
            const count = frames.length;
            const samplePosition = cyclePhase * count;
            const center = Math.floor(samplePosition);
            const t = samplePosition - center;
            const t2 = t * t;
            const t3 = t2 * t;
            const w0 = (1 - 3 * t + 3 * t2 - t3) / 6;
            const w1 = (4 - 6 * t2 + 3 * t3) / 6;
            const w2 = (1 + 3 * t + 3 * t2 - 3 * t3) / 6;
            const w3 = t3 / 6;
            const f0 = frames[(center - 1 + count) % count];
            const f1 = frames[center % count];
            const f2 = frames[(center + 1) % count];
            const f3 = frames[(center + 2) % count];
            for (let i = 0; i < positions.length; i++) {
                positions[i] = f0[i] * w0 + f1[i] * w1 + f2[i] * w2 + f3[i] * w3;
            }
            drawBody();
            finGroup.setAttribute("transform", fitFin(positions));
        };

        const place = () => {
            let bob = 0;
            if (heave.length) {
                const p = phase * heave.length;
                const k = Math.floor(p);
                const t = p - k;
                bob = (heave[k % heave.length] * (1 - t) + heave[(k + 1) % heave.length] * t) * HEAVE * whaleW;
            }
            wrapper.style.transform = `translate3d(${x.toFixed(2)}px, ${bob.toFixed(2)}px, 0) scaleX(${dir})`;
        };

        const measure = () => {
            containerW = container.clientWidth;
            whaleW = svg.getBoundingClientRect().width;
            speed = window.matchMedia("(min-width: 48rem)").matches ? DESKTOP.speed : MOBILE.speed;
            if (reduceMotion) {
                x = (containerW - whaleW) / 2;
                place();
            }
        };

        const startSwim = () => {
            x = dir === 1 ? -whaleW : containerW;
            swimming = true;
            place();
            wrapper.style.visibility = "visible";
            maybeRun();
        };

        const tick = (time: number) => {
            rafId = 0;
            if (!swimming || !visible || document.hidden || !data) return;
            const dt = lastTime ? Math.min(time - lastTime, 100) / 1000 : 0;
            lastTime = time;

            x += dir * speed * dt;
            // Tail beat tied to travel speed so the whale doesn't look like it's sliding.
            const strokeSeconds = (BODY_LENGTHS_PER_STROKE * whaleW) / speed;
            phase = (phase + dt / strokeSeconds) % 1;
            place();
            if (time - lastPathTime >= PATH_FRAME_MS) {
                lastPathTime = time;
                drawShape(phase);
            }

            const offscreen = dir === 1 ? x >= containerW : x <= -whaleW;
            if (offscreen) {
                swimming = false;
                wrapper.style.visibility = "hidden";
                restTimer = setTimeout(() => {
                    dir = -dir;
                    startSwim();
                }, REST_MIN_MS + Math.random() * (REST_MAX_MS - REST_MIN_MS));
                return;
            }
            rafId = requestAnimationFrame(tick);
        };

        function maybeRun() {
            if (reduceMotion || rafId || !swimming || !visible || document.hidden || !data) return;
            lastTime = 0;
            rafId = requestAnimationFrame(tick);
        }

        const onData = (loaded: WhaleInk) => {
            if (disposed) return;
            data = loaded;
            frames = loaded.frames.map((frame) => Float32Array.from(frame));
            positions = new Float32Array(frames[0].length);
            const n = loaded.ring.length;
            ringX = new Float32Array(n);
            ringY = new Float32Array(n);
            tmpX = new Float32Array(n);
            tmpY = new Float32Array(n);
            segments = new Array(n);
            fitFin = makeAffineFit(frames[0], loaded.fin);

            // Body heave tied to the tail beat, in counter-phase with the tail tip: while the fluke
            // sweeps up the body sinks, and while it sweeps down the body rises.
            const tipY = frames.map(
                (f) => loaded.tailTip.reduce((sum, i) => sum + f[loaded.ring[i] * 2 + 1], 0) / loaded.tailTip.length,
            );
            const meanY = tipY.reduce((sum, y) => sum + y, 0) / tipY.length;
            const raw = tipY.map((y) => meanY - y); // screen y points down, so tail up → positive → body down
            const peak = Math.max(...raw.map(Math.abs)) || 1;
            heave = Float32Array.from(raw, (v) => v / peak);
            for (const [name, d] of Object.entries(loaded.art)) {
                svg.querySelector(`[data-art="${name}"]`)?.setAttribute("d", d);
            }

            measure();
            drawShape(0);
            if (reduceMotion) {
                wrapper.style.visibility = "visible";
            } else {
                dir = 1;
                startSwim();
            }
        };

        // Only fetch the drawing once the footer is getting close.
        const loadObserver = new IntersectionObserver(
            (entries) => {
                if (!entries.some((e) => e.isIntersecting)) return;
                loadObserver.disconnect();
                import("@/app/data/whaleInk.json").then((m) => onData(m.default as WhaleInk));
            },
            { rootMargin: "400px" },
        );
        loadObserver.observe(container);

        // Only animate while the footer is actually on screen.
        const visibleObserver = new IntersectionObserver((entries) => {
            visible = entries.some((e) => e.isIntersecting);
            if (visible) maybeRun();
        });
        visibleObserver.observe(container);

        const onVisibilityChange = () => {
            if (!document.hidden) maybeRun();
        };
        document.addEventListener("visibilitychange", onVisibilityChange);

        const resizeObserver = new ResizeObserver(() => {
            if (data) measure();
        });
        resizeObserver.observe(container);

        return () => {
            disposed = true;
            if (rafId) cancelAnimationFrame(rafId);
            clearTimeout(restTimer);
            loadObserver.disconnect();
            visibleObserver.disconnect();
            resizeObserver.disconnect();
            document.removeEventListener("visibilitychange", onVisibilityChange);
        };
    }, [reduceMotion]);

    return (
        <div
            ref={containerRef}
            aria-hidden="true"
            className="relative w-full h-[46px] md:h-[70px] mt-6 overflow-hidden pointer-events-none"
        >
            <div
                ref={wrapperRef}
                className="absolute left-0 top-[2px] will-change-transform"
                style={{ visibility: "hidden" }}
            >
                <svg
                    ref={svgRef}
                    viewBox={`0 0 ${VIEW_W} ${VIEW_H}`}
                    overflow="visible"
                    className="block w-[107px] md:w-[171px] h-auto"
                >
                    <defs>
                        <path id={`${id}-body`} ref={bodyRef} d="" />
                        <clipPath id={`${id}-clip`}>
                            <use href={`#${id}-body`} />
                        </clipPath>
                    </defs>
                    {/* Near pectoral fin, tucked under the body. */}
                    <g ref={finRef}>
                        <path data-art="fin" fill="var(--whale-paper)" />
                        {/* Pen outline and tip hatching, as filled shapes so they scale with the whale. */}
                        <path data-art="finInk" fill="var(--whale-ink)" />
                    </g>
                    <use href={`#${id}-body`} fill="var(--whale-ink)" />
                    {/* Throat pleats, trimmed to the live body outline. */}
                    <g clipPath={`url(#${id}-clip)`}>
                        <path data-art="throatBase" fill="var(--whale-pleat)" />
                        <path data-art="strands" fill="var(--whale-paper)" />
                        <path data-art="prefin" fill="var(--whale-paper)" />
                    </g>
                    <path data-art="farFin" fill="var(--whale-ink)" />
                    <g ref={flukeRef}>
                        <path data-art="fluke" fill="var(--whale-ink)" />
                    </g>
                </svg>
            </div>
        </div>
    );
}
