// Shared drawing + swim cycle for the ink-style humpback whales (footer and contact page).
//
// Humpback whale mesh from the whale kit (CC BY 4.0, see /THIRD_PARTY_NOTICES.txt), drawn in
// the style of the kit's ink showcase render. whaleInk.json holds 30 keyframes (periodic cubic
// B-spline) of the mesh vertices the drawing tracks, plus static ink artwork in rest-frame
// coordinates:
//   - the body is a smooth closed curve through a ring of outline vertices,
//   - the throat strands/pleats are clipped to that live body outline,
//   - the fin art follows a least-squares affine fit of its vertices,
//   - the fluke art is anchored between the tail stock and tail tip of that outline.
// The data file is generated by scripts/whale/build-whale-ink.mjs (`npm run whale:build`, see
// scripts/whale/README.md); this module only animates it.

export type WhaleInk = {
    frames: number[][]; // per keyframe: x,y of each tracked vertex
    ring: number[]; // body outline, as indices into the tracked vertices
    fin: number[];
    tailTip: number[]; // ring positions averaged into the tail tip
    tailStock: number[]; // ring positions averaged into the tail stock (fluke root)
    art: Record<string, string>; // d attributes, keyed by data-art name
};

export type WhaleEls = {
    svg: SVGSVGElement;
    body: SVGPathElement;
    fin: SVGGElement;
    fluke: SVGGElement;
};

export type WhaleRig = {
    /**
     * Pose the whale's shape at swim-cycle phase 0..1. `flex.undulation` (≈ tail effort, 1 = cruise)
     * scales a travelling wave down the spine; `flex.bend` (−1..1) curves the body into a turn.
     */
    draw(els: WhaleEls, phase: number, flex?: { undulation?: number; bend?: number }): void;
    /** Body heave at phase 0..1, normalised to ±1 (positive = belly-ward). */
    heaveAt(phase: number): number;
};

// Must match the mesh bounds the data was generated with — hardcoded so containers have their
// final size before the (lazy-loaded) data arrives.
export const VIEW_W = 904;
export const VIEW_H = 338;

export const BODY_LENGTHS_PER_STROKE = 1.2; // how far one tail beat carries the whale
export const PATH_FRAME_MS = 33; // shape redraws capped at ~30fps; translation stays per-frame
export const HEAVE = 0.012; // peak vertical body heave per tail beat, as a fraction of whale length
// The mesh's swim cycle barely flexes the body (it's nearly all tail), so a travelling wave is added
// down the spine, head to tail, arriving at the tail in step with the tail beat.
const SPINE_WAVE = 60; // mesh units (body ≈ 900) of spine flex at full effort, before the envelope
const SPINE_WAVELENGTH = 1.1; // body lengths per spine wave (cetaceans ≈ 1–1.2)
const TURN_BEND = 30; // mesh units the tail end swings toward a turn at the full turning rate
const clamp01 = (v: number) => (v < 0 ? 0 : v > 1 ? 1 : v);
const SMOOTH_PASSES = 12; // Taubin smoothing of the outline ring (removes mesh jitter without shrinking)

let inkPromise: Promise<WhaleInk> | null = null;

/** Lazily loads whaleInk.json once; every whale on the page shares the same chunk and parse. */
export function loadWhaleInk(): Promise<WhaleInk> {
    inkPromise ??= import("@/app/data/whaleInk.json").then((m) => m.default as WhaleInk);
    return inkPromise;
}

/** Fills the static artwork paths (marked with data-art) inside a WhaleSvg. */
export function applyWhaleArt(svg: SVGSVGElement, data: WhaleInk) {
    for (const [name, d] of Object.entries(data.art)) {
        svg.querySelector(`[data-art="${name}"]`)?.setAttribute("d", d);
    }
}

// Least-squares affine map from rest positions to current positions for a vertex group.
// The normal matrix only depends on the rest pose, so it's inverted once up front.
function makeAffineFit(rest: Float32Array, verts: number[]) {
    let a00 = 0, a01 = 0, a02 = 0, a11 = 0, a12 = 0, a22 = 0;
    for (const v of verts) {
        const x = rest[v * 2];
        const y = rest[v * 2 + 1];
        a00 += x * x; a01 += x * y; a02 += x; a11 += y * y; a12 += y; a22 += 1;
    }
    const c00 = a11 * a22 - a12 * a12;
    const c01 = a02 * a12 - a01 * a22;
    const c02 = a01 * a12 - a02 * a11;
    const c11 = a00 * a22 - a02 * a02;
    const c12 = a01 * a02 - a00 * a12;
    const c22 = a00 * a11 - a01 * a01;
    const det = a00 * c00 + a01 * c01 + a02 * c02;
    const i00 = c00 / det, i01 = c01 / det, i02 = c02 / det;
    const i11 = c11 / det, i12 = c12 / det, i22 = c22 / det;

    return (pos: Float32Array) => {
        let bx0 = 0, bx1 = 0, bx2 = 0, by0 = 0, by1 = 0, by2 = 0;
        for (const v of verts) {
            const x = rest[v * 2];
            const y = rest[v * 2 + 1];
            const px = pos[v * 2];
            const py = pos[v * 2 + 1];
            bx0 += x * px; bx1 += y * px; bx2 += px;
            by0 += x * py; by1 += y * py; by2 += py;
        }
        const a = i00 * bx0 + i01 * bx1 + i02 * bx2;
        const c = i01 * bx0 + i11 * bx1 + i12 * bx2;
        const e = i02 * bx0 + i12 * bx1 + i22 * bx2;
        const b = i00 * by0 + i01 * by1 + i02 * by2;
        const d = i01 * by0 + i11 * by1 + i12 * by2;
        const f = i02 * by0 + i12 * by1 + i22 * by2;
        return `matrix(${a.toFixed(4)} ${b.toFixed(4)} ${c.toFixed(4)} ${d.toFixed(4)} ${e.toFixed(2)} ${f.toFixed(2)})`;
    };
}

/**
 * Precomputes everything needed to pose whales from the data. One rig can drive any number of
 * whales: draw() writes straight into the given elements and keeps no per-whale state.
 */
export function createWhaleRig(data: WhaleInk): WhaleRig {
    const frames = data.frames.map((frame) => Float32Array.from(frame));
    const positions = new Float32Array(frames[0].length);
    const n = data.ring.length;
    let ringX = new Float32Array(n);
    let ringY = new Float32Array(n);
    let tmpX = new Float32Array(n);
    let tmpY = new Float32Array(n);
    const segments = new Array<string>(n);
    const fitFin = makeAffineFit(frames[0], data.fin);

    // Body heave tied to the tail beat, in counter-phase with the tail tip: while the fluke
    // sweeps up the body sinks, and while it sweeps down the body rises.
    const tipY = frames.map(
        (f) => data.tailTip.reduce((sum, i) => sum + f[data.ring[i] * 2 + 1], 0) / data.tailTip.length,
    );
    const meanY = tipY.reduce((sum, y) => sum + y, 0) / tipY.length;
    const raw = tipY.map((y) => meanY - y); // screen y points down, so tail up → positive → body down
    const peak = Math.max(...raw.map(Math.abs)) || 1;
    const heave = Float32Array.from(raw, (v) => v / peak);

    // Spine flex: the body's rest-frame extent (head at high x) and the tail's phase in the cycle,
    // so the added wave reaches the tail in step with the mesh's own tail beat.
    let headX = -Infinity;
    let tailX = Infinity;
    for (const i of data.ring) {
        headX = Math.max(headX, frames[0][i * 2]);
        tailX = Math.min(tailX, frames[0][i * 2]);
    }
    const bodyLength = Math.max(1, headX - tailX);
    let sinSum = 0;
    let cosSum = 0;
    tipY.forEach((y, k) => {
        const a = (2 * Math.PI * k) / tipY.length;
        sinSum += (y - meanY) * Math.sin(a);
        cosSum += (y - meanY) * Math.cos(a);
    });
    const tailPhase = Math.atan2(cosSum, sinSum); // tail tip offset ≈ R·sin(2π·phase + tailPhase)

    const drawBody = (els: WhaleEls) => {
        const ring = data.ring;
        for (let i = 0; i < n; i++) {
            ringX[i] = positions[ring[i] * 2];
            ringY[i] = positions[ring[i] * 2 + 1];
        }
        // Taubin smoothing: alternate shrink/inflate passes so the outline loses the
        // mesh's zig-zag without the whole whale getting thinner.
        for (let pass = 0; pass < SMOOTH_PASSES; pass++) {
            const lambda = pass % 2 ? -0.53 : 0.5;
            for (let i = 0; i < n; i++) {
                const prev = (i - 1 + n) % n;
                const next = (i + 1) % n;
                tmpX[i] = ringX[i] + lambda * ((ringX[prev] + ringX[next]) / 2 - ringX[i]);
                tmpY[i] = ringY[i] + lambda * ((ringY[prev] + ringY[next]) / 2 - ringY[i]);
            }
            [ringX, tmpX] = [tmpX, ringX];
            [ringY, tmpY] = [tmpY, ringY];
        }
        // The fluke art is drawn in a local frame running from the tail stock (0) to the
        // tail tip (1) of the smoothed outline, so it can't drift off the body.
        let sx = 0, sy = 0, tx = 0, ty = 0;
        for (const i of data.tailStock) { sx += ringX[i]; sy += ringY[i]; }
        for (const i of data.tailTip) { tx += ringX[i]; ty += ringY[i]; }
        sx /= data.tailStock.length; sy /= data.tailStock.length;
        tx /= data.tailTip.length; ty /= data.tailTip.length;
        const ax = tx - sx;
        const ay = ty - sy;
        els.fluke.setAttribute(
            "transform",
            `matrix(${ax.toFixed(3)} ${ay.toFixed(3)} ${(-ay).toFixed(3)} ${ax.toFixed(3)} ${sx.toFixed(2)} ${sy.toFixed(2)})`,
        );
        // Closed Catmull-Rom spline through the smoothed ring, as cubic Béziers.
        for (let i = 0; i < n; i++) {
            const i0 = (i - 1 + n) % n;
            const i2 = (i + 1) % n;
            const i3 = (i + 2) % n;
            segments[i] =
                `C${(ringX[i] + (ringX[i2] - ringX[i0]) / 6).toFixed(1)} ${(ringY[i] + (ringY[i2] - ringY[i0]) / 6).toFixed(1)} ` +
                `${(ringX[i2] - (ringX[i3] - ringX[i]) / 6).toFixed(1)} ${(ringY[i2] - (ringY[i3] - ringY[i]) / 6).toFixed(1)} ` +
                `${ringX[i2].toFixed(1)} ${ringY[i2].toFixed(1)}`;
        }
        els.body.setAttribute("d", `M${ringX[0].toFixed(1)} ${ringY[0].toFixed(1)}${segments.join("")}Z`);
    };

    return {
        draw(els, phase, flex) {
            const count = frames.length;
            const samplePosition = phase * count;
            const center = Math.floor(samplePosition);
            const t = samplePosition - center;
            const t2 = t * t;
            const t3 = t2 * t;
            const w0 = (1 - 3 * t + 3 * t2 - t3) / 6;
            const w1 = (4 - 6 * t2 + 3 * t3) / 6;
            const w2 = (1 + 3 * t + 3 * t2 - 3 * t3) / 6;
            const w3 = t3 / 6;
            const f0 = frames[(center - 1 + count) % count];
            const f1 = frames[center % count];
            const f2 = frames[(center + 1) % count];
            const f3 = frames[(center + 2) % count];
            for (let i = 0; i < positions.length; i++) {
                positions[i] = f0[i] * w0 + f1[i] * w1 + f2[i] * w2 + f3[i] * w3;
            }
            const undulation = flex?.undulation ?? 1;
            const bend = flex?.bend ?? 0;
            if (undulation !== 0 || bend !== 0) {
                // Travelling wave down the spine (head → tail), growing toward the tail, plus a curve
                // into turns with the head steady and the tail swinging. Applied to every tracked
                // vertex, so the outline, fin and fluke all flex together.
                const base = 2 * Math.PI * phase + tailPhase;
                const k = (2 * Math.PI) / SPINE_WAVELENGTH;
                for (let i = 0; i < positions.length; i += 2) {
                    const u = clamp01((headX - positions[i]) / bodyLength); // 0 at the head, 1 at the tail
                    positions[i + 1] +=
                        undulation * SPINE_WAVE * u * u * (1 - 0.6 * u) * Math.sin(base + k * (1 - u)) +
                        bend * TURN_BEND * u * u;
                }
            }
            drawBody(els);
            els.fin.setAttribute("transform", fitFin(positions));
        },
        heaveAt(phase) {
            const p = phase * heave.length;
            const k = Math.floor(p);
            const t = p - k;
            return heave[k % heave.length] * (1 - t) + heave[(k + 1) % heave.length] * t;
        },
    };
}
